### ISSUE TITLE
TechDivision_SystemConfigDiff_Helper_Config::getDisplaysettingsAliasThis() 

### ISSUE THREAD

**Issue by fplantinet** [techdivision/TechDivision_SystemConfigDiff#1]
Fatal error: Call to undefined method TechDivision_SystemConfigDiff_Helper_Config::getDisplaysettingsAliasThis() in /app/code/community/TechDivision/SystemConfigDiff/Block/Adminhtml/Overview/Tabs/SystemConfig.php on line 86

**Comment by fplantinet** [comment]
And in config : 
Fatal error: Call to undefined method TechDivision_SystemConfigDiff_Helper_Config::getDisplaysettingsShowDiff() in /app/code/community/TechDivision/SystemConfigDiff/Model/Observer.php on line 46

**Comment by sydekumf** [comment]
Seems like I forgot some helper methods to commit. I added them now, please have a look if the error occurs and give me a short feedback, so I can close this issue :-)

**Comment by fplantinet** [comment]
Yes,
Now when active system diff we have :  
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'preprod.techdivision_systemconfigdiff_diff_config' doesn't exist

and i core_ressource : 
techdivision_systemconfigdiff_setup
${release.version}
${release.version

i remove core_ressource and add 0.1.0beta in config.xml

after i have i config : 
"NetworkError: 404 Not Found - skin/adminhtml/base/default/css/techdivision/systemconfigdiff/diff.css"
diff.css
"NetworkError: 404 Not Found - skin/adminhtml/base/default/js/techdivision/systemconfigdiff/jquery-1.9.1.min.js"
jquery....min.js
"NetworkError: 404 Not Found - skin/adminhtml/base/default/js/techdivision/systemconfigdiff/diff.js"

i move your entreprise skin en default skin :)

and now i try your very promising module!

I connect prod in preprod and i try, but Button : New Diff = nothing
And when i active "Show diff in system config" = nothing in systemconfig

I check conflict, no conflict with existing module.

how i can debug then ?

**Comment by sydekumf** [comment]
Hi, I am very sorry for this but there was some problem with commiting the correct files to github. You are right, the version in config.xml was missing, so I added it now.
To reinstall your module, you need to go to the `core_ressource` table in your database and delete the entry for `TechDivision_SystemConfigDiff`. Also look for tables which start with `techdivision_` and delete them.
After that you can reload your Adminhtml and the module should install correctly now.

The skin files: Are you using community version? I suspect that it can't fiind the files because they are in the enterprise folder. If this i the case (I will check it) I will commit it in another folder, so community can use it.

But thanks a lot for your feedback until now! It helps a lot to improve the module :-)

**Comment by sydekumf** [comment]
I updated the skin folder now. Please reinstall the module as I described above and install it again. Please let me know if it works. Thanks!

**Comment by fplantinet** [comment]
Thanx, i update.
New diff load many time and nothing after.
And in system > configuration we have nothing.
We have create user api in prod en i test in preprod to synch some value en preprod.

**Comment by sydekumf** [comment]
Sry, I could not understand what you have done exactly. The loading/calculation of the diff can take some time, thats normal. Did you wait until it finished? Any error messages? Is there some log output in `var/log/system.log` or `var/log/exception.log` or `/tmp/php_error.log`?
I think you are french, aren't you? If it is easier for you, you can also answer in french :-)

**Comment by fplantinet** [comment]
Merci pour votre réponse !
Je referai des tests de diff de config jeudi ou vendredi.

J'ai un bug sur un menu d'un module amasty : 
Fatal error: Call to a member function setTemplate() on a non-object in app/code/community/TechDivision/SystemConfigDiff/Model/Observer.php on line 59

**Comment by sydekumf** [comment]
Pouvez vous appeler le nom du module amasty avec le numéro de version que vous employez? Quel menu est-ce?
