### ISSUE TITLE
Fatal error: Call to undefined method TechDivision_SystemConfigDiff_Helper_Config::getDisplaysettingsShowDiff() in app/code/community/TechDivision/SystemConfigDiff/Model/Observer.php on line 46

### ISSUE THREAD

**Issue by paales** [techdivision/TechDivision_SystemConfigDiff#3]

**Comment by paales** [comment]
More errors:

```
 Fatal error: Call to undefined method TechDivision_SystemConfigDiff_Helper_Config::getDisplaysettingsIgnorePaths() in app/code/community/TechDivision/SystemConfigDiff/Helper/Data.php on line 37
```

it seems I'm missing some code, seems this repo isn't updated to the latest version, care to update the repo?

**Comment by romiro** [comment]
Have this same error. Method does not exist.

**Comment by sydekumf** [comment]
I am so sorry guys, it is embarrasing but I struggle a lot with git. So you were right, the code was missing, indeed it has been added in the past and then deleted again if you look into the commit history.. :-) But anyway, I commited it again, so it should work now. Please confirm shortly if the error message dissapears so I can close this here. Thanks guys!

**Comment by paales** [comment]
I advise to develop using modman
https://github.com/colinmollenhour/modman
http://www.aschroder.com/2011/02/magento-development-and-deployment-setting-up-a-modman-based-magento-project-on-magento-1-5/

This way you can easily add this repository as a submodule to your main project. Changes can be easily pulled and pushed to this repository.
