### ISSUE TITLE
SOAP error: Function ("systemConfigGetConfig") is not a valid method for this service

### ISSUE THREAD

**Issue by riker09** [techdivision/TechDivision_SystemConfigDiff#4]
I'm getting this error whenever I'm trying to do a diff.

I created a soap user and an appropriate soap role with access to everything.

**Comment by riker09** [comment]
Almost in the same instant that I've opened this issue I realized what the problem was: I only installed the module on the target system. I think the documentation should be improved and point out that the module needs to be installed on **both** systems.

**Comment by twosg** [comment]
I am getting the same error message, BUT I have installed the module on both systems. Any suggestion?

**Comment by riker09** [comment]
Wow, a three year old issue. :smile:

I'm just guessing here. Maybe SOAP isn't available on one of the systems or the SOAP calls are blocked by configuration and/or firewall?

I haven't used this module ever since. I'm trying to put all my configuration either in config.xml nodes or in setup scripts. This way everything is under version control and I can roll out my shops with a simple `git push` + `git pull`.

**Comment by aingham** [comment]
Hi @twosg - did you manage to resolve your problem, as I'm experiencing the same issue?

**Comment by twosg** [comment]
Hi @aingham 
Yes but I am not sure how I solved it :P I think I saved the configuration several times as well as flushed the cache. In the end, it was working, but I did not really work with it because I needed it for a Magento 1.5 project (yes such things still exist) and did not use it.

**Comment by aingham** [comment]
Wow @twosg - that was a fast reply! I played around a bit more and in the end found that my problem was due to my having specified the API url as https; when I changed this over to http it worked.
