### ISSUE TITLE
Showing config differences even when path listed in Ignored Paths

### ISSUE THREAD

**Issue by aingham** [techdivision/TechDivision_SystemConfigDiff#8]
Sometimes it seems to show a difference in a path even though it's listed in the ignored paths (system->Configuration->SystemConfigDiff):

![image](https://cloud.githubusercontent.com/assets/3470609/18464957/f41595c8-798b-11e6-8e6c-50320cc9fbb8.png)

![image](https://cloud.githubusercontent.com/assets/3470609/18465042/78eacb60-798c-11e6-8832-f0e8666260ee.png)

N.B. I did make sure to run a 'New Diff' after having specified the ignore path.

**Comment by sydekumf** [comment]
Hi,
the ignore paths are only for the display in the system configuration (the red dots, and red markings). In the grid you still will see all differences :-)

**Comment by aingham** [comment]
Hi Florian - thanks for getting back on this. I did work that out later, but forgot to update my comment. I think what would work well is if there was an extra column in the diff listing which was a yes/no, depending on whether path is in the ignore paths. One could then choose to see all diffs or filter out the ones in ignore paths. I'll have a look at making this change at some point. Cheers.
